#!/bin/sh

# save as .git/hooks/prepare-commit-msg and make it executable

prepend_branch_name() {
  COMMIT_MSG_FILE=$1
  # prepend default commit message with current git branch name
  GIT_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
  # if branch name has forward slash (/) in it, only use last fragment following slash
  GIT_BRANCH_NAME_LAST_SEGMENT=$(echo $GIT_BRANCH_NAME | sed -e "s/.*\///")
  # create temp file with new message followed by default message, then move to original filename
  echo "$GIT_BRANCH_NAME_LAST_SEGMENT \n" | cat - $COMMIT_MSG_FILE > $COMMIT_MSG_FILE.bak && mv $COMMIT_MSG_FILE{.bak,}
}

case "$2,$3" in # ugh
  ,|template,)
    # only normal or template commits (not e.g. merges)
    prepend_branch_name $1
    ;;
  *)
    ;;
esac
