# some recommendations from https://alliance.seas.upenn.edu/~bcpierce/wiki/index.php?n=Main.UnisonFAQOSSpecific#osx

rsrc = false

ignore = Name .fseventsd
ignore = Name .FBCIndex
ignore = Name .FBCLockFolder
ignore = Name Cache*
ignore = Name .Trash*
ignore = Name .VolumeIcon.icns
ignore = Name .HSicon
ignore = Name Temporary*
ignore = Name .Temporary*
ignore = Name TheFindByContentFolder
ignore = Name TheVolumeSettingsFolder
ignore = Name .Metadata
ignore = Name .filler
ignore = Name .idsff
ignore = Name .Spotlight*
ignore = Name .DS_Store
ignore = Name .CFUserTextEncoding
ignore = Name .DocumentRevisions-V100
