# some recommendations from https://alliance.seas.upenn.edu/~bcpierce/wiki/index.php?n=Main.UnisonFAQOSSpecific#osx

# docs for options:
# https://www.cis.upenn.edu/~bcpierce/unison/download/releases/stable/unison-manual.html

rsrc = false

# ignore = Name .*
ignore = Name .CFUserTextEncoding
ignore = Name .DS_Store
ignore = Name .DocumentRevisions-V100
ignore = Name .FBCIndex
ignore = Name .FBCLockFolder
ignore = Name .HSicon
ignore = Name .Metadata
ignore = Name .Spotlight*
ignore = Name .Temporary*
ignore = Name .Trash*
ignore = Name .VolumeIcon.icns
ignore = Name .filler
ignore = Name .fseventsd
ignore = Name .idsff
ignore = Name Cache*
ignore = Name Temporary*
ignore = Name TheFindByContentFolder
ignore = Name TheVolumeSettingsFolder
